id: redditappi0d
secret: apps
password: password
agent: gif searcher
username: mimi9102
sub: test
author: mimi9102
GiphyAuth: giphyauth
ImgurAuth: Client-ID imgurAuth
SplashAuth: splashAuth
dbConnString: host=hostname dbname=georgeDb user=uid password=pasword
